version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0  # Using the official MySQL image
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: microservices_db
    ports:
      - "3306:3306"
    networks:
      - microservices-net

  # Eureka Proxy (Discovery Server)
  eureka-proxy:
    build:
      context: ./eureka-proxy  # Build from the eureka-server directory
    container_name: eureka-proxy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  # User Service (Spring Boot)
  user-service:
    build:
      context: ./user-service  # Build from the user-service directory
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      EUREKA_SERVER_URL: http://eureka-proxy:8761/eureka/
    ports:
      - "8086:8086"
    depends_on:
      - mysql
      - eureka-proxy
    networks:
      - microservices-net

  # Order Service (Spring Boot)
  # order-service:
  #   build:
  #     context: ./order-service  # Build from the order-service directory
  #   container_name: order-service
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_db
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: rootpassword
  #     EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - mysql
  #     - eureka-server
  #   networks:
  #     - microservices-net

networks:
  microservices-net:
    driver: bridge
